### ISSUE TITLE
/proc/ not mounted on boot of c2 [indigo]

### ISSUE THREAD

**Issue by TheDash** [pr2-debs/pr2-netboot#5]
Proc can be mounted later after login via ssh or serial connection, after that most bugs go away.

**Comment by v4hn** [comment]
This seems to be obsolete. `/proc` mounts fine on our system.
and I believe it already did when we got the servers back from you @TheDash .
Can't test this anymore though...

**Comment by TheDash** [comment]
I think this is old too, i'll close it.
